version: 0.2

phases:
  install:
    commands:
      - echo "Updating package lists..."
      - yum -y update
      - echo "Installing Amazon Corretto 22..."
      - yum -y install java-22-amazon-corretto-devel
      - echo "Setting environment variables..."
      - ./set-env.sh
      - echo "Installing dependencies..."
      - source ./set-env.sh && mvn install
  build:
    commands:
      - echo "Building the project..."
      - source ./set-env.sh && mvn clean package
artifacts:
  files:
    - target/demo-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - server_stop.sh
    - server_start.sh

