version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing dependencies..."
      - mvn install
  build:
    commands:
      - echo "Building the project..."
      - mvn clean package
artifacts:
  files:
    - target/demo-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - server_stop.sh
    - server_start.sh
