version: 0.2

env:
  variables:
    JAVA_HOME: /usr/lib/jvm/java-22-amazon-corretto
    PATH: /usr/lib/jvm/java-22-amazon-corretto/bin:$PATH

phases:
  install:
    runtime-versions:
      java: corretto22
    commands:
      - echo "Installing dependencies..."
      - mvn install
  build:
    commands:
      - echo "Building the project..."
      - mvn clean package
artifacts:
  files:
    - target/demo-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - server_stop.sh
    - server_start.sh

