version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto-22
    commands:
      - echo "Installing dependencies..."
      - yum -y install java-22-amazon-corretto-devel.x86_64
      - JAVA_HOME=/usr/lib/jvm/java-22-amazon-corretto
      - PATH=$JAVA_HOME/bin:$PATH
      - mvn install
  build:
    commands:
      - echo "Building the project..."
      - JAVA_HOME=/usr/lib/jvm/java-22-amazon-corretto
      - PATH=$JAVA_HOME/bin:$PATH
      - mvn clean package
artifacts:
  files:
    - target/demo-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - server_stop.sh
    - server_start.sh

