version: 0.2

env:
  variables:
    JAVA_HOME: /usr/lib/jvm/java-17-amazon-corretto
    PATH: /usr/lib/jvm/java-17-amazon-corretto/bin:$PATH

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Updating packages..."
      - sudo yum -y update
      - echo "Installing Amazon Corretto 17..."
      - sudo yum -y install java-17-amazon-corretto-devel
  build:
    commands:
      - echo "Building the project..."
      - mvn clean install
artifacts:
  files:
    - target/demo-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - server_stop.sh
    - server_start.sh
