version: 0.2

phases:
  install:
    commands:
      - echo "Updating package lists..."
      - yum -y update
      - echo "Installing Amazon Corretto 17..."
      - yum -y install java-17-amazon-corretto-devel
      - echo "Installing Maven..."
      - yum -y install maven

  pre_build:
    commands:
      - echo "Setting JAVA_HOME and PATH..."
      - export JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto
      - export PATH=$JAVA_HOME/bin:$PATH
      - echo "JAVA_HOME is set to $JAVA_HOME"
      - echo "PATH is set to $PATH"
      - echo "Creating script to run Maven commands..."
      - |
        cat << 'EOF' > run_maven.sh
        #!/bin/bash
        export JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto
        export PATH=$JAVA_HOME/bin:$PATH
        echo "JAVA_HOME is set to $JAVA_HOME"
        echo "PATH is set to $PATH"
        echo "Checking Maven version..."
        java -version
        mvn --version
        EOF
      - chmod +x run_maven.sh
      - ./run_maven.sh

  build:
    commands:
      - echo "Build started on `date`"
      - echo "Compiling the Maven project..."
      - ./run_maven.sh mvn compile
      - echo "Running tests..."
      - ./run_maven.sh mvn test
      - echo "Packaging the application..."
      - ./run_maven.sh mvn package

artifacts:
  files:
    - '**/*'
 
